### ISSUE TITLE
[Feat] 상품 정보 페이지 1

### ISSUE THREAD

**Issue by Joygarden425** [KMS-SmartCart/SmartCart-frontend#6]
## Description
카메라로 찍은 상품 정보(상품명, 가격) 보여주는 페이지

## In Progress
- [ ] 상품 정보 중 상품명이 상품명에 알맞게 들어감
- [ ] 가격이 가격란에 알맞게 들어감
- [ ] 용량이 용량란에 알맞게 들어감
- [ ] 사용자가 상품 정보 수정 가능

**Comment by tkguswls1106** [comment]
Issue #6 -> #10 전환으로 인하여, 이슈를 닫았습니다.
